pool:
  vmImage: "windows-2022"

trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: pipelines/build.yml
  - stage: Deploy
    jobs:
      - deployment: Test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "deploy"
