pool:
  vmImage: "windows-2022"

trigger:
  - master

variables:
  - name: AdminEmails
    value: "gundersen@gmail.com, erikly@gmail.com"
  - name: FromEmail
    value: pamelding@bardarswingclub.no

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: pipelines/build.yml

  - stage: DeployTest
    displayName: Deploy to Test
    condition: false
    jobs:
      - deployment: Test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipelines/deploy.yml
                  parameters:
                    appName: bsc-medlemmer-test

  - stage: DeployProd
    displayName: Deploy to Prod
    dependsOn: [Build]
    jobs:
      - deployment: Prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipelines/deploy.yml
                  parameters:
                    appName: bsc-medlemmer
