pool:
  vmImage: "windows-2022"

trigger:
  - master

variables:
  - name: AdminEmails
    value: "gundersen@gmail.com, erikly@gmail.com"
  - name: FromEmail
    value: pamelding@bardarswingclub.no
  - name: azureSubscription
    value: bsc-medlemmer
  - name: appName
    value: bsc-medlemmer
  - name: resourceGroup
    vaule: bsc-medlemmer-rg

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: pipelines/build.yml

  - stage: DeployTest
    displayName: Deploy to Test
    jobs:
      - deployment: Test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipelines/deploy.yml
                  parameters:
                    appName: $(appName)
                    azureSubscription: $(azureSubscription)
                    resourceGroup: $(resourceGroup)

  - stage: DeployProd
    displayName: Deploy to Prod
    jobs:
      - deployment: Prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureAppServiceManage@0
                  inputs:
                    azureSubscription: $(azureSubscription)
                    Action: Swap Slots
                    WebAppName: $(appName)
                    ResourceGroupName: $(resourceGroup)
                    SourceSlot: test
