pool:
  name: Hosted VS2017

trigger:
  - master

variables:
  BuildConfiguration: release

steps:
  - task: UseDotNet@2
    displayName: ".NET Core 5 for building"
    inputs:
      version: "5.0.x"
      packageType: sdk

  - task: UseDotNet@2
    displayName: ".NET Core 3.1.x"
    inputs:
      version: "3.1.x"
      packageType: runtime

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "**/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*.Tests.csproj"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: "--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)"
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      ArtifactName: "Drop"
