steps:
  - task: UseDotNet@2
    displayName: ".NET Core 6 for building"
    inputs:
      version: "6.0.x"
      packageType: sdk

  - task: Cache@2
    inputs:
      key: 'nuget | "$(Agent.OS)"'
      restoreKeys: |
        nuget | "$(Agent.OS)"
      path: $(Build.SourcesDirectory)/.nuget/packages
    displayName: Cache NuGet packages

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "**/*.csproj"
      arguments: "--configuration release"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*.Tests.csproj"
      arguments: "--configuration release"
      nobuild: true

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: "--configuration release --output $(build.artifactstagingdirectory)"
      zipAfterPublish: True

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: WebApp
    displayName: "Publish artifact WebApp"
