name: Build and deploy

on:
  push:
    branches:
    - master
env:
  AdminEmails: gundersen@gmail.com, erikly@gmail.com
  FromEmail: pamelding@bardarswingclub.no
  azureSubscription: bsc-medlemmer
  appName: bsc-medlemmer
  resourceGroup: bsc-medlemmer-rg
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: .NET Core 6 for building
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        key: nuget | "${{ runner.os }}"
        restore-keys:
          nuget | "${{ runner.os }}"
        path: ${{ github.workspace }}/.nuget/packages
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration release
    - name: Publish
      run: dotnet publish --no-restore --no-build --configuration release --output output
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        path: output
        filename: webapp.zip
    - name: Publish artifact WebApp
      uses: actions/upload-artifact@v3
      with:
        path: webapp.zip
        name: WebApp

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: Test
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: WebApp
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.appName }}
        package: webapp.zip
        slot-name: test

  Swap:
    runs-on: windows-latest
    needs: Deploy
    environment:
      name: Prod
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/cli@v1.0.0
      with:
        inlineScript: az webapp deployment slot swap --resource-group ${{ env.resourceGroup }} --name ${{ env.appName }} --slot test --target-slot production
